import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'msedge'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
await page.route('**/profile-estate/auth/me',route=>route.fulfill({json:{success:true,data:{username:'tester'}}}));
await page.addInitScript(()=>sessionStorage.setItem('nt-studio-session','test-token'));
await page.goto(process.env.STUDIO_TEST_URL || 'http://127.0.0.1:5173');
await page.locator('ion-button.hydrated').first().waitFor();
await page.evaluate(()=>document.fonts.ready);
await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
assert.equal(await page.locator('#app').getAttribute('data-ui-theme'),'dark');
await page.locator('#ui-theme-toggle').click();
assert.equal(await page.locator('#app').getAttribute('data-ui-theme'),'light');
assert.equal(await page.locator('#ui-theme-toggle').getAttribute('aria-pressed'),'true');
await page.screenshot({path:'artifacts/desktop-light.png',fullPage:true});
await page.reload();
await page.locator('ion-button.hydrated').first().waitFor();
assert.equal(await page.locator('#app').getAttribute('data-ui-theme'),'light');
await page.locator('#ui-theme-toggle').click();
assert.equal(await page.locator('#app').getAttribute('data-ui-theme'),'dark');
const fittedWidth=await page.locator('#slide-holder').evaluate(el=>el.getBoundingClientRect().width);
await page.locator('#zoom-in').click();
assert.equal(await page.locator('#zoom-reset').textContent(),'110%');
assert((await page.locator('#slide-holder').evaluate(el=>el.getBoundingClientRect().width))>fittedWidth);
assert(await page.locator('.slide-stage').evaluate(el=>el.scrollWidth>el.clientWidth||el.scrollHeight>el.clientHeight));
assert(await page.evaluate(()=>document.querySelector('#slide .slide-header').getBoundingClientRect().top>=document.querySelector('.slide-stage').getBoundingClientRect().top),'Zoom must keep the slide header visible');
await page.locator('.slide-stage').evaluate(el=>{el.scrollTop=el.scrollHeight;});
assert(await page.evaluate(()=>document.querySelector('#slide .slide-footer').getBoundingClientRect().bottom<=document.querySelector('.slide-stage').getBoundingClientRect().bottom+1),'Slide footer must remain reachable when zoomed');
assert(await page.evaluate(()=>document.querySelector('#app').scrollHeight<=innerHeight+1));
await page.locator('#zoom-out').click();
assert.equal(await page.locator('#zoom-reset').textContent(),'100%');
await page.setViewportSize({width:2048,height:1064});
await page.locator('#zoom-in').click();
assert(await page.evaluate(()=>{const stage=document.querySelector('.slide-stage').getBoundingClientRect(),slide=document.querySelector('#slide').getBoundingClientRect();return slide.left>=stage.left&&slide.right<=stage.right&&slide.top>=stage.top&&slide.bottom<=stage.bottom;}),'At 2048x1064, 110% must show the full slide');
assert(await page.evaluate(()=>document.querySelector('#app').scrollHeight<=innerHeight+1),'Zoom must not add page scrolling');
await page.locator('#expand').click();
await page.waitForFunction(()=>document.querySelector('.slide-stage').clientWidth>1200);
assert(await page.locator('.workspace').evaluate(el=>el.classList.contains('expanded')),'Preview should enter expanded mode');
assert(await page.locator('.slide-stage').evaluate(el=>el.clientWidth>1200),'Expanded preview should use the full available workspace');
await page.locator('#expand').click();
assert(await page.locator('.workspace').evaluate(el=>!el.classList.contains('expanded')),'Preview should return to edit mode');
await page.locator('#zoom-reset').click();
await page.setViewportSize({width:1440,height:1000});
await page.locator('#zoom-out').click();
assert.equal(await page.locator('#zoom-reset').textContent(),'90%');
await page.locator('#zoom-reset').click();
assert.equal(await page.locator('#zoom-reset').textContent(),'100%');
await page.locator('#inline-edit').click();
assert.equal(await page.locator('#inline-edit').getAttribute('aria-pressed'),'true');
await page.locator('#slide h2').fill('ชื่อที่แก้บนสไลด์');
assert.equal(await page.locator('[data-field=title]').inputValue(),'ชื่อที่แก้บนสไลด์');
await page.locator('.selling-points li').first().fill('จุดเด่นที่แก้บนสไลด์');
await page.locator('[data-tab=points]').click();
assert.match(await page.locator('[data-field=points]').inputValue(),/จุดเด่นที่แก้บนสไลด์/);
await page.locator('.target-tags span').first().fill('ธุรกิจใหม่');
assert.match(await page.locator('#form-panel [data-tag-index="0"]').inputValue(),/ธุรกิจใหม่/);
await page.locator('[data-add-tag]').click();
assert.equal(await page.locator('.target-tags span').count(),5);
await page.locator('[data-tag-highlight="4"]').click();
assert.match(await page.locator('.target-tags span').last().getAttribute('class'),/highlighted/);
await page.locator('[data-tag-delete="4"]').click();
assert.equal(await page.locator('.target-tags span').count(),4);
await page.locator('.detail-column dt').first().fill('พื้นที่รวม');
await page.locator('#inline-edit').click();
assert.equal(await page.locator('#slide h2').getAttribute('contenteditable'),'false');
const tagWasHighlighted=await page.locator('#slide [data-tag-index="0"]').getAttribute('aria-pressed');
await page.locator('#slide [data-tag-index="0"]').click();
assert.notEqual(await page.locator('#slide [data-tag-index="0"]').getAttribute('aria-pressed'),tagWasHighlighted);
await page.locator('#slide [data-tag-index="0"]').press('Space');
assert.equal(await page.locator('#slide [data-tag-index="0"]').getAttribute('aria-pressed'),tagWasHighlighted);
await page.locator('[data-field=caveats]').fill('ทางเข้า / ออกแคบ\n\nตรวจสอบสภาพอาคาร');
assert.equal(await page.locator('.caveats li').count(),2);
await page.locator('[data-field=footerRight]').fill('ข้อความท้ายสไลด์จากแท็บจุดเด่น');
assert.equal(await page.locator('.slide-footer span').last().textContent(),'ข้อความท้ายสไลด์จากแท็บจุดเด่น');
await page.locator('#inline-edit').click();
await page.locator('.caveats li').first().fill('ทางเข้า / ออกใช้ร่วมกัน');
assert.match(await page.locator('[data-field=caveats]').inputValue(),/ทางเข้า \/ ออกใช้ร่วมกัน/);
await page.locator('#inline-edit').click();
await page.locator('#save').click();
await page.reload();
await page.locator('ion-button.hydrated').first().waitFor();
assert.equal(await page.locator('.detail-column dt').first().textContent(),'พื้นที่รวม');
assert.equal(await page.locator('#slide h2').textContent(),'ชื่อที่แก้บนสไลด์');
assert.equal(await page.locator('.caveats li').first().textContent(),'ทางเข้า / ออกใช้ร่วมกัน');
assert.equal(await page.locator('.slide-footer span').last().textContent(),'ข้อความท้ายสไลด์จากแท็บจุดเด่น');
await page.locator('[data-tab=profile]').click();
await page.locator('[data-field=title]').fill('ชุมสายพระโขนง ทดสอบ');
assert.match(await page.locator('#slide h2').textContent(),/ทดสอบ/);
await page.locator('#save').click();await page.reload();
await page.locator('ion-button.hydrated').first().waitFor();
assert.match(await page.locator('[data-field=title]').inputValue(),/ทดสอบ/);
await page.locator('[data-field=title]').fill('ชุมสายพระโขนง');
await page.locator('[data-field=mapUrl]').fill('https://maps.google.com/?q=13.7,100.6');
assert.match(await page.locator('#map-preview-link').getAttribute('href'),/maps.google.com/);
assert.equal(await page.locator('#map-preview-link').getAttribute('target'),'_blank');
assert.match(await page.locator('#map-preview-link').textContent(),/เปิดใน Google Maps/);
assert.equal(await page.locator('.location-strip').evaluate(el=>el.tagName),'DIV','Slide coordinate strip should not be clickable as a whole');
await page.locator('[data-tab=style]').click();
await page.locator('[data-theme=modern-navy]').click();
assert.match(await page.locator('#slide').getAttribute('class'),/modern-navy-theme/);
await page.locator('[data-theme=corporate-yellow]').click();
await page.locator('[data-field=density]').selectOption('compact');
assert.match(await page.locator('#slide').getAttribute('class'),/compact-density/);
await page.locator('[data-field=footerRight]').fill('เอกสารภายใน');
assert.equal(await page.locator('.slide-footer span').last().textContent(),'เอกสารภายใน');
await page.locator('[data-tab=media]').click();
assert.equal(await page.locator('[data-camera]').count(),5,'Every image slot should offer a camera');
assert.equal(await page.locator('[data-select-upload]').count(),5,'Every image slot should offer file upload');
const chooserPromise=page.waitForEvent('filechooser');
await page.locator('[data-select-upload=photo]').click();
await (await chooserPromise).setFiles('public/assets/exterior.jpg');
await page.waitForFunction(()=>document.querySelector('#slide img').src.startsWith('data:'));
await page.locator('[data-reset=photo]').click();
await page.locator('[data-upload=photo1]').setInputFiles('public/assets/exterior.jpg');
await page.waitForFunction(()=>document.querySelector('.site-photo img').src.startsWith('data:'));
await page.locator('[data-reset=photo1]').click();
await page.locator('[data-field=dimTop]').fill('หน้ากว้าง 40 ม.');
assert.match(await page.locator('[data-dimension=dimTop]').textContent(),/40/);
await page.locator('[data-check=showDimensions]').uncheck();
assert.match(await page.locator('.dimension-overlay').getAttribute('class'),/hidden/);
await page.locator('[data-check=showDimensions]').check();
await page.locator('#export').click();
for(const format of ['png','pptx']){
 const download=page.waitForEvent('download',{timeout:60000});
 await page.locator('[data-format='+format+']').click();
 await (await download).saveAs('artifacts/slide.'+format);
 await page.waitForFunction(()=>document.querySelector('#export-status').textContent==='ส่งออกเรียบร้อยแล้ว');
}
const imageData='data:image/png;base64,'+(await readFile('artifacts/slide.png')).toString('base64');
assert(await page.evaluate(async src=>{const img=new Image();img.src=src;await img.decode();const c=document.createElement('canvas');c.width=120;c.height=68;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,120,68);return ctx.getImageData(0,0,120,68).data.some((v,i)=>i%4!==3&&v<100);},imageData),'PNG must contain visible content');
await page.locator('#close-dialog').click();
await page.locator('[data-tab=profile]').click();
for(const [width,height] of [[2048,1064],[1440,900],[1366,768],[1024,768]]){
 await page.setViewportSize({width,height});
 await page.waitForTimeout(100);
 const layout=await page.evaluate(()=>{
  const stage=document.querySelector('.slide-stage').getBoundingClientRect();
  const holder=document.querySelector('#slide-holder').getBoundingClientRect();
  return {appScroll:document.querySelector('#app').scrollHeight,viewport:innerHeight,
   slideInside:holder.top>=stage.top-1&&holder.bottom<=stage.bottom+1,
   previewBottom:document.querySelector('.sample-note').getBoundingClientRect().bottom};
 });
 assert(layout.appScroll<=layout.viewport+1,`Desktop page scrolls at ${width}x${height}`);
 assert(layout.slideInside,`Slide is clipped at ${width}x${height}`);
 assert(layout.previewBottom<=height+1,`Preview content is clipped at ${width}x${height}`);
 if(width===2048) await page.screenshot({path:'artifacts/desktop-fit.png',fullPage:true});
}
for(const width of [1440,1024,768,390,360]){
 await page.setViewportSize({width,height:900});
 await page.waitForTimeout(200);
 assert(await page.evaluate(()=>document.querySelector('#app').scrollWidth<=innerWidth+1),'Page overflow at '+width);
 if(width===390){
  await page.screenshot({path:'artifacts/mobile-edit.png',fullPage:true});
  await page.locator('#ui-theme-toggle').click();
  assert.equal(await page.locator('#app').getAttribute('data-ui-theme'),'light');
  assert(await page.evaluate(()=>document.querySelector('#app').scrollWidth<=innerWidth+1));
  await page.screenshot({path:'artifacts/mobile-light.png',fullPage:true});
  await page.locator('#ui-theme-toggle').click();
  await page.locator('#inline-edit').click();
  assert.equal(await page.locator('.workspace').getAttribute('data-view'),'preview');
  assert.equal(await page.locator('#slide h2').getAttribute('contenteditable'),'true');
  await page.locator('#inline-edit').click();
  await page.locator('ion-segment-button[value=preview]').click();
  await page.screenshot({path:'artifacts/mobile-preview.png',fullPage:true});
  assert(await page.locator('.preview-area').isVisible());
  await page.locator('#zoom-in').click();
  assert.equal(await page.locator('#zoom-reset').textContent(),'110%');
  assert(await page.evaluate(()=>document.querySelector('#app').scrollWidth<=innerWidth+1));
  await page.locator('#zoom-reset').click();
  await page.locator('ion-segment-button[value=edit]').click();
 }
}
assert.deepEqual(errors,[]);
console.log('PASS: live editing, persistence, themes, image upload, PNG/PPTX exports, 5 viewport sizes; no page errors.');
await browser.close();
