import { escapeHTML as esc, fields } from './model';
import { mapHref } from './slide';
import { pointsFormMarkup } from './points-form';

const icon = name => `<i data-lucide="${name}" aria-hidden="true"></i>`;
const input = (data, key, label, multi = false) => `<label class="field"><span>${label}</span>${multi ? `<textarea data-field="${key}" rows="3">${esc(data[key] ?? '')}</textarea>` : `<input data-field="${key}" value="${esc(data[key] ?? '')}" ${['lat', 'lng'].includes(key) ? 'inputmode="decimal"' : ''}>`}</label>`;
const select = (data, key, label, options) => `<label class="field"><span>${label}</span><select data-field="${key}">${options.map(([value, text]) => `<option value="${value}" ${data[key] === value ? 'selected' : ''}>${text}</option>`).join('')}</select></label>`;
const imageChoices = (key, label) => `<div class="image-choices" role="group" aria-label="เพิ่ม${label}"><button type="button" class="image-choice" data-camera="${key}">${icon('camera')} ถ่ายรูป</button><button type="button" class="image-choice" data-select-upload="${key}">${icon('upload')} อัปโหลดรูป</button><input ${key === 'photo' ? 'id="photo-upload"' : ''} data-upload="${key}" type="file" accept="image/jpeg,image/png,image/webp" aria-label="เลือกไฟล์${label}" hidden></div><p class="image-help">JPG, PNG หรือ WebP ไม่เกิน 5 MB</p>`;
const upload = (key, label, image, fit, caption = '') => `<div class="media-card"><h4>${label}</h4><img class="upload-preview" src="${esc(image)}" alt="${label}">${imageChoices(key, label)}${fit ? select({[key + 'Fit']: fit}, key + 'Fit', 'การจัดภาพ', [['cover','เต็มกรอบ'],['contain','เห็นทั้งภาพ']]) : ''}${caption ? input({[caption.key]:caption.value},caption.key,'คำบรรยายภาพ') : ''}<button type="button" class="text-button" data-reset="${key}">ใช้ภาพตัวอย่าง</button></div>`;

export function formMarkup(tab, data) {
  if (tab === 'profile') return `<section class="form-section"><h3><span class="step">1</span> ข้อมูลหลัก</h3>${input(data,'propertyCode','รหัสทรัพย์สิน')}${input(data,'cdgId','รหัสกลุ่มพื้นที่ CDG')}${input(data,'title','ชื่อทรัพย์สิน / โครงการ')}${input(data,'category','ประเภททรัพย์สิน')}</section><section class="form-section"><h3><span class="step">2</span> รายละเอียดพื้นที่</h3>${fields.map(([key,label])=>input(data,key,label,['building','transport'].includes(key))).join('')}${input(data,'price','ราคา / เงื่อนไข')}</section><section class="form-section"><div class="coordinate-heading"><h3><span class="step">3</span> พิกัดทรัพย์สิน</h3><div class="coordinate-actions"><button type="button" class="coordinate-action" data-coordinate-source="current">ตำแหน่งปัจจุบัน</button><button type="button" class="coordinate-action" data-coordinate-source="server" ${data.propertyId ? '' : 'disabled'}>ตำแหน่งจากเซิร์ฟเวอร์</button></div></div><div class="coordinate-fields">${input(data,'lat','ละติจูด')}${input(data,'lng','ลองจิจูด')}</div>${input(data,'mapUrl','Google Maps URL (ถ้ามี)')}<a id="map-preview-link" class="map-open-link" href="${esc(mapHref(data))}" target="_blank" rel="noopener noreferrer">${icon('map')} เปิดใน Google Maps ${icon('arrow-up-right')}</a></section>`;
  if (tab === 'points') return pointsFormMarkup(data);
  if (tab === 'media') return `<section class="form-section"><h3>แผนที่หรือภาพหลัก</h3>${upload('photo','ภาพแผนที่',data.photo,data.photoFit)}${select(data,'photoPos','ตำแหน่งภาพ',[['center','กึ่งกลาง'],['top','ด้านบน'],['bottom','ด้านล่าง']])}<label class="field checkbox-field"><input type="checkbox" data-check="showDimensions" ${data.showDimensions?'checked':''}> แสดงกรอบขนาดพื้นที่</label><div class="dimension-fields">${input(data,'dimTop','ด้านบน')}${input(data,'dimBottom','ด้านล่าง')}${input(data,'dimLeft','ด้านซ้าย')}${input(data,'dimRight','ด้านขวา')}</div></section><section class="form-section"><h3>รูปประกอบ 3 ช่อง</h3>${[1,2,3].map(i=>upload('photo'+i,'รูปประกอบ '+i,data['photo'+i],data['photo'+i+'Fit'],{key:'caption'+i,value:data['caption'+i]})).join('')}</section><section class="form-section"><h3>โลโก้บนสไลด์</h3>${data.logoPhoto?`<img class="upload-preview logo-preview" src="${esc(data.logoPhoto)}" alt="โลโก้ที่เลือก">`:''}${imageChoices('logoPhoto','โลโก้')}<button type="button" data-reset="logoPhoto" class="text-button">ใช้โลโก้ NT</button></section>`;
  if (tab === 'style') return `<section class="form-section"><h3>ธีมสไลด์</h3><div class="theme-options">${[['corporate-yellow','Corporate Yellow'],['modern-navy','Modern Navy'],['emerald-green','Emerald Green'],['luxury-red','Luxury Red']].map(([value,label])=>`<button type="button" data-theme="${value}" aria-pressed="${data.theme===value}" class="theme-option ${data.theme===value?'selected':''}"><span class="theme-swatch ${value}"></span>${label}${data.theme===value?icon('check'):''}</button>`).join('')}</div></section><section class="form-section"><h3>ความหนาแน่นข้อความ</h3>${select(data,'density','รูปแบบการจัดข้อความ',[['normal','มาตรฐาน'],['compact','กระชับ'],['ultracompact','กระชับมาก']])}<button type="button" data-auto-fit class="text-button">${icon('scan')} จัดข้อความให้พอดีอัตโนมัติ</button></section><section class="form-section"><h3>ส่วนท้ายสไลด์</h3>${input({footerRight:data.slideLabels?.footerRight ?? '© National Telecom All Rights Reserved'},'footerRight','ข้อความท้ายสไลด์')}</section><section class="form-section"><h3>การส่งออก</h3><button type="button" data-print class="text-button">${icon('printer')} พิมพ์สไลด์</button><p class="muted">สไลด์แนวนอน 16:9</p></section>`;
  return '';
}


